import { Ticket } from '../../core/domain/ticket';
import { User360 } from '../../core/domain/user';
import { AuditEntry } from '../../core/domain/audit';
import { EmailDelivery, EmailTemplate, SendBroadcastPayload, SendEmailPayload } from '../../core/domain/email';
import { PageRequest, PageResult } from '../../core/domain/page';
import { Operator } from '../../core/domain/operator';
import { ITicketRepository, TicketFilters } from '../../core/ports/ticket-repository.port';
import { IUserRepository } from '../../core/ports/user-repository.port';
import { IAuditRepository, AuditFilters } from '../../core/ports/audit-repository.port';
import { IEmailService } from '../../core/ports/email-service.port';
import { IAuthService } from '../../core/ports/auth-service.port';
import { ApiClient, ApiError } from './api-client';
import { NewsletterSubscriber, NewsletterPayload, NewsletterCampaign } from '../../core/domain/email';

const idPath = (id: string) => encodeURIComponent(id);

export class HttpTicketRepository implements ITicketRepository {
  constructor(private readonly client: ApiClient) {}
  listPage(filters: TicketFilters, pagination: PageRequest) {
    return this.client.page<Ticket>('/frontdesk/tickets', { ...filters, ...pagination });
  }
  async list(filters: TicketFilters = {}) { return (await this.listPage(filters, { page: 0, size: 25 })).items; }
  getById(id: string) { return this.client.nullable<Ticket>(`/frontdesk/tickets/${idPath(id)}`); }
  createTicket(ticket: Parameters<ITicketRepository['createTicket']>[0], initialMessage: string) {
    const { userId, userEmail, userName, subject, category, priority, metadata } = ticket;
    return this.client.request<Ticket>('/frontdesk/tickets', {
      method: 'POST', body: { userId, userEmail, userName, subject, category, priority, metadata, initialMessage },
    });
  }
  addMessage(ticketId: string, message: Parameters<ITicketRepository['addMessage']>[1]) {
    return this.client.request<Ticket>(`/frontdesk/tickets/${idPath(ticketId)}/messages`, {
      method: 'POST', body: { content: message.content, isInternalNote: Boolean(message.isInternalNote) },
    });
  }
  updateStatus(ticketId: string, status: Ticket['status']) {
    return this.client.request<Ticket>(`/frontdesk/tickets/${idPath(ticketId)}/status`, { method: 'PATCH', body: { status } });
  }
  assignOperator(ticketId: string, operatorId: string, _operatorName: string) {
    return this.client.request<Ticket>(`/frontdesk/tickets/${idPath(ticketId)}/assignee`, { method: 'PATCH', body: { operatorId } });
  }
}

export class HttpUserRepository implements IUserRepository {
  constructor(private readonly client: ApiClient) {}
  searchPage(query: string, pagination: PageRequest) { return this.client.page<User360>('/frontdesk/users', { query, ...pagination }); }
  async search(query: string) { return (await this.searchPage(query, { page: 0, size: 25 })).items; }
  getById(id: string) { return this.client.nullable<User360>(`/frontdesk/users/${idPath(id)}`); }
  updateStatus(userId: string, status: User360['status']) {
    return this.client.request<User360>(`/frontdesk/users/${idPath(userId)}/status`, { method: 'PATCH', body: { status } });
  }
  resetAiQuota(userId: string) {
    return this.client.request<User360>(`/frontdesk/users/${idPath(userId)}/ai-quota/reset`, { method: 'POST' });
  }
}

export class HttpAuditRepository implements IAuditRepository {
  constructor(private readonly client: ApiClient) {}
  listPage({ targetUserId, action }: AuditFilters, pagination: PageRequest) {
    return this.client.page<AuditEntry>('/frontdesk/audit', { targetUserId, action, ...pagination });
  }
  async list(filters: AuditFilters = {}) {
    return (await this.listPage(filters, { page: 0, size: Math.min(filters.limit || 25, 100) })).items;
  }
  async logEvent(_entry: Parameters<IAuditRepository['logEvent']>[0]): Promise<AuditEntry> {
    throw new ApiError(405, 'Audit is generated by the server', 'UNSUPPORTED_FEATURE');
  }
}

export class HttpEmailService implements IEmailService {
  constructor(private readonly client: ApiClient) {}
  listSubscribers(query: string, tier: string, pagination: PageRequest) {
    return this.client.page<NewsletterSubscriber>('/frontdesk/newsletter/subscribers', { query, tier, ...pagination });
  }
  sendNewsletter(payload: NewsletterPayload) {
    return this.client.request<NewsletterCampaign>('/frontdesk/newsletter/campaigns', { method: 'POST', body: payload });
  }
  getCampaign(id: string) {
    return this.client.request<NewsletterCampaign>(`/frontdesk/newsletter/campaigns/${idPath(id)}`);
  }
  listCampaigns(pagination: PageRequest) {
    return this.client.page<NewsletterCampaign>('/frontdesk/newsletter/campaigns', { ...pagination });
  }
  listTemplates() { return this.client.request<EmailTemplate[]>('/frontdesk/email-templates'); }
  async listDeliveries(pagination: PageRequest): Promise<PageResult<EmailDelivery>> {
    const page = await this.client.page<EmailDelivery>('/frontdesk/emails', { ...pagination });
    // Deliberately do not expose the stored recipient ciphertext in the view model.
    return { ...page, items: page.items.map(({ id, recipientName, subject, status, createdAt, sentAt, messageId }) =>
      ({ id, recipientName, subject, status, createdAt, sentAt, messageId })) };
  }
  async sendEmail(payload: SendEmailPayload) {
    const result = await this.client.request<{ success: boolean; messageId: string }>('/frontdesk/emails', { method: 'POST', body: payload });
    if (!result?.success) throw new ApiError(502, 'Email was not accepted');
    return result;
  }
  async sendBroadcast(_payload: SendBroadcastPayload): Promise<{ success: boolean; recipientCount: number }> {
    throw new ApiError(501, 'Broadcasts are not available', 'UNSUPPORTED_FEATURE');
  }
  renderTemplate(templateId: string, variables: Record<string, string>) {
    return this.client.request<{ subject: string; body: string }>(`/frontdesk/email-templates/${idPath(templateId)}/render`, {
      method: 'POST', body: { variables },
    });
  }
}

export class HttpAuthService implements IAuthService {
  constructor(private readonly client: ApiClient) {}
  async currentOperator() {
    const operator = await this.client.request<Operator>('/frontdesk/me');
    if (!operator || typeof operator.id !== 'string' || !operator.id || typeof operator.name !== 'string' || operator.role !== 'OPERATOR') {
      throw new ApiError(0, 'Invalid operator response', 'INVALID_RESPONSE');
    }
    return operator;
  }
  async signIn(username: string, password: string) {
    await this.client.request('/users/login', { method: 'POST', body: { username, password }, csrf: false });
    return this.currentOperator();
  }
  async signOut() {
    try { await this.client.request('/users/logout', { method: 'POST', csrf: false }); }
    catch (error) {
      // A session which has already expired is locally signed out too; network failures are not success.
      if (!(error instanceof ApiError) || error.status !== 401) throw error;
    }
    this.client.endSession();
  }
  googleLoginUrl() { return `${this.client.baseUrl}/oauth2/authorization/google`; }
  onAccessFailure(listener: (status: number) => void) { return this.client.onAccessFailure(listener); }
}
